### ISSUE TITLE
VS 2017 compile error

### ISSUE THREAD

**Issue by bftjoe** [pothitos/naxos#1]
Hi,

I am trying to compile with VS2017 Community Edition, but I get this error.

E0413	no suitable conversion function from "std::ofstream" to "bool" exists c:\naxos\core\naxos.h	1249

Please help.

**Comment by pothitos** [comment]
Thank you for the issue, Joseph!

I think that [this also occurs](https://travis-ci.org/pothitos/naxos/jobs/193861056#L333) in newer GCC versions, like 6 :slightly_frowning_face:

As I have a very tight schedule, I'm not so confident on when I'll fix these. Perhaps in a month, except if I receive a pull request earlier...

**Comment by bftjoe** [comment]
I submitted a pull request. Please look at it when you have the time.
