### ISSUE TITLE
We need more example

### ISSUE THREAD

**Issue by dry11orange** [pothitos/naxos#10]
such as sudoku, Einstein's Riddle.

**Comment by pothitos** [comment]
Hello and thanks for reaching out 👋

Regarding sudoku, take a look at [apps/for_amorgos/sudoku.cpp](https://github.com/pothitos/naxos/blob/master/apps/for_amorgos/sudoku.cpp).

Anyway, for better or worse, I've now finished my research and PhD and don't work on this anymore but in industry and an irrelevant side-project.

I leave this open. If anyone wants to contribute, they're more than welcome 🙏

**Comment by dry11orange** [comment]
👍😊
