### ISSUE TITLE
Grid representation

### ISSUE THREAD

**Issue by alxhotel** [pothitos/naxos#4]
What is the best type to use as a representation of a grid?

A `NsIntVarArray`?
A `NsDeque<NsDeque<NsInt>>` ?
Or is there something more convenient?

**Comment by pothitos** [comment]
Thank you, Alex, for your question!

I quote the [section](https://github.com/pothitos/naxos/blob/master/manual/Arrays.md#how-to-implement-a-grid-of-constrained-variables) I added right now to the manual, hoping that it'll help you.

> In general, there's a flexibility using such kinds of data structures. In any case, an easy implementation follows when you know a priori how many `lines` the grid will contain.
> 
> ```C++
> NsDeque<NsIntVarArray> grid(lines);
> ```
> 
> You will be then able to add constrained variables to the array of line `l` by using the `push_back` method. For example, the following alternative cases are possible.
> 
> ```C++
> grid[l].push_back(NsIntVar(pm, 0, 1));
> ```
> 
> ```C++
> NsIntVar X(pm, -2, 10);
> grid[l].push_back(X);
> ```
> 
> ```C++
> grid[l].push_back(another_grid[3][4]);
> ```

**Comment by alxhotel** [comment]
Thanks! :+1:
